name = "2intenzbot"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# DISCORD_APPLICATION_ID = ""
# DISCORD_PUBLIC_KEY = ""
# DISCORD_TOKEN = ""
# DISCORD_GUILD_ID = ""
# DISCORD_CHANNEL_ID = ""

[[kv_namespaces]]
binding = "LIIGA_KV"
id = "682df7a7edc44fb49e569863f1a4e0fb"

[[d1_databases]]
binding = "DB"
database_name = "2intenzbot"
database_id = "074a8322-9628-452a-b512-51205027873e"

[triggers]
crons = ["* * * * *", "0 21 * * SUN"] # Every minute for tracking, Sunday 21:00 for results
